pipelines:
  default:
    - step:
        script:
          - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
          - for ruby_version in 2.5 2.6 2.7 3.0 2 3; do
          - for node_version in 10 12 14 16; do
          - docker build --build-arg RUBY_VERSION=$ruby_version --build-arg NODE_VERSION=$node_version --build-arg VERSION=0 -t hinderlingvolkart/noderuby-build:$ruby_version-$node_version noderuby-build/
          - docker push hinderlingvolkart/noderuby-build:$ruby_version-$node_version
          - done; done
options:
  docker: true