pipelines:
  branches:
    master:
      - step:
          name: Node images
          script:
            - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
            - for node_version in 10 12 14 15 16 18 19; do
            - echo "--- NODE $node_version ---"
            - docker build --build-arg NODE_VERSION=$node_version --build-arg VERSION=$BITBUCKET_BUILD_NUMBER -t hinderlingvolkart/node-build:$node_version node-build/
            - docker push hinderlingvolkart/node-build:$node_version
            - done
      - step:
          name: Node and Ruby images
          script:
            - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
            - for ruby_version in 2.5 2.6 2.7 2 3; do
            - for node_version in 12 14 16 18; do
            - |
              BUNDLER_VERSION="2.0"
              if (( $(echo "$ruby_version < 2.6" | bc -l) )); then
                BUNDLER_VERSION="2.3.26"
              fi
            - echo "--- RUBY $ruby_version / NODE $node_version / BUNDLER $BUNDLER_VERSION ---"
            - docker build --build-arg RUBY_VERSION=$ruby_version --build-arg NODE_VERSION=$node_version --build-arg BUNDLER_VERSION=$BUNDLER_VERSION --build-arg VERSION=$BITBUCKET_BUILD_NUMBER -t hinderlingvolkart/noderuby-build:$ruby_version-$node_version noderuby-build/
            - docker push hinderlingvolkart/noderuby-build:$ruby_version-$node_version
            - done; done
options:
  docker: true