#!/bin/bash

##### CONSTANTS

VERSION=1.2

RESTORE='\033[0m'

RED='\033[00;31m'
GREEN='\033[00;32m'
YELLOW='\033[00;33m'
BLUE='\033[00;34m'
PURPLE='\033[00;35m'
CYAN='\033[00;36m'
LIGHTGRAY='\033[00;37m'


##### ARGUMENTS

source_directory=./build
project=$BITBUCKET_REPO_SLUG
site_name=$project
destination=netlify

while [ "$1" != "" ]; do
    case $1 in
        -s | --source )         shift
                                source_directory=$1
                                ;;
        -n | --name )           shift
                                site_name=$1
                                ;;
        -p | --project )        shift
                                project=$1
                                ;;
        * )                     exit 1
    esac
    shift
done

echo -e "${YELLOW}HV PUBLISH ${PURPLE}${VERSION}${RESTORE}"
echo -e "${YELLOW}-----------${YELLOW}---${RESTORE}"


COMMIT_SUBJECT=`git log -n 1 --pretty=format:%s $BITBUCKET_COMMIT`
COMMIT_DATE=`git log -n 1 --pretty="format:%cI" $BITBUCKET_COMMIT`
COMMIT_AUTHOR=`git log -n 1 --pretty="format:%aN <%ae>" $BITBUCKET_COMMIT`




echo '{
	"repo_slug": "'$BITBUCKET_REPO_SLUG'",
	"commit_hash": "'$BITBUCKET_COMMIT'",
	"commit_message": "'${COMMIT_SUBJECT//\"/\\\"}'",
	"commit_date": "'$COMMIT_DATE'",
	"branch": "'$BITBUCKET_BRANCH'",
	"build_number": "'$BITBUCKET_BUILD_NUMBER'"
}' > $source_directory/netlify-deploy.json

output=/tmp/url.txt

netlify-deploy --source $source_directory --name $site_name --output $output --message "${COMMIT_SUBJECT//\"/\\\"}"

deploy_url=`cat $output`

node -p "JSON.stringify({url:'$deploy_url', commit: '$BITBUCKET_COMMIT', branch: '$BITBUCKET_BRANCH', project: '$project', message: '${COMMIT_SUBJECT//\'/\\\'}', comitted_at: '$COMMIT_DATE', author: '$COMMIT_AUTHOR'})" > body.json

echo -e "🏦  ${CYAN}Saving deploy to ${YELLOW}Firebase${RESTORE}"

cat body.json

# Save to HVify (firebase)
curl -s -k -H "Content-Type: application/json" -X POST -d @body.json "https://hvify.com/api/deploy?token=$HVIFY_TOKEN"
